services:
 - &acc
  name: acc
  image: nginx:latest
  check:
   mode: http
   ping: /status_acc
   pong: ok
  parameters:
   - "-p=80"
  uses:
   - *dictionary
   - *db
   - *pcc

 - &pcc
  name: pcc
  image: nginx:latest
  check:
   mode: http
   ping: /status_pcc
   pong: ok
  parameters:
   - "-p=80"
  uses:
   - *dictionary
   - *db

 - &dictionary
  name: dic
  image: nginx:latest
  check:
   mode: http
   ping: /status_dic
   pong: ok
  parameters:
   - "-p=80"
  uses:
   - *db
   - *cache

 - &db
  name: db
  image: nginx:latest
  check:
   mode: tcp
   ping: telnet
   pong: ok
  parameters:
   - "-p=80"
   - "--net=host"
  uses:
   - *cache
   - *cache

 - &cache
  name: cache
  image: nginx:latest
  parameters:
   - "-p=8080"
   - "--net=bridge"
  uses: