services:
 - &acc
  name: acc
  image: latam:acc
  command: echo hola acc
  check:
   mode: http
   ping: /status
   pong: ok
  parameters:
   - "-p=80"
  uses:
   - *dictionary
   - *db
   - *pcc

 - &pcc
  name: pcc
  image: latam:pcc
  command: echo hola pcc
  check:
   mode: http
   ping: /status
   pong: ok
  parameters:
   - "-p=80"
  uses:
   - *dictionary
   - *db

 - &dictionary
  name: dic
  image: latam:dic
  command: echo hola dic
  check:
   mode: http
   ping: /status
   pong: ok
  parameters:
   - "-p=80"
  uses:
   - *db
   - *cache

 - &db
  name: db
  image: debian:wheezy
  command: echo hola db
  check:
   mode: tcp
   ping: telnet
   pong: ok
  parameters:
   - "-p=80"
   - "--net=host"
  uses:
   - *cache
   - *cache

 - &cache
  name: cache
  image: centos:centos6
  command: echo hola cache
  parameters:
   - "-p=8080"
   - "--net=bridge"
  uses: