services:
 acc: &acc
  image: latam:acc
  command: echo hola acc
  check:
   mode: http
   ping: /status
   pong: ok
  parameters:
   - "-p=80"
  uses:
   - *dictionary
   - *db
   - *pcc

 pcc: &pcc
  image: latam:pcc
  command: echo hola pcc
  parameters:
   - "-p=80"
  uses:
   - *dictionary
   - *db

 dic: &dictionary
  image: latam:dic
  command: echo hola dic
  parameters:
   - "-p=80"
  uses:
   - *db
   - *cache

 db: &db
  image: debian:wheezy
  command: echo hola db
  parameters:
   - "-p=80"
   - "--net=host"
  uses:
   - *cache
   - *cache

 cache: &cache
  image: centos:centos6
  command: echo hola cache
  parameters:
   - "-p=8080"
   - "--net=bridge"
  uses: