services:
 - &acc
  name: acc
  config:
   Image: nginx:latest
  hostconfig:
   PublishAllPorts: true
  check:
   mode: http
   ping: /status_acc
   pong: ok
  uses:
   - *dictionary
   - *db
   - *pcc

 - &pcc
  name: pcc
  config:
   Image: nginx:latest
  hostconfig:
   PublishAllPorts: true
  check:
   mode: http
   ping: /status_pcc
   pong: ok
  uses:
   - *dictionary
   - *db

 - &dictionary
  name: dic
  config:
   Image: nginx:latest
  hostconfig:
   PublishAllPorts: true
  check:
   mode: http
   ping: /status_dic
   pong: ok
  uses:
   - *db
   - *cache

 - &db
  name: db
  config:
   Image: nginx:latest
  hostconfig:
   PublishAllPorts: true
  check:
   mode: tcp
   ping: telnet
   pong: ok
  uses:
   - *cache
   - *cache

 - &cache
  name: cache
  config:
   Image: nginx:latest
  hostconfig:
   PublishAllPorts: true
  uses: