process:
  lan: &lan
    import:
      - *proc_compra
      - *proc_checkin
  
  compra: &proc_compra
    mount:
      - *cache
  checkin: &proc_checkin
    import:
      - *proc_vasientos

  vasientos: &proc_vasientos
    mount:
      - *db

  hybrid: &proc_hyb


services:
  - &db
    name: db
    image: debian:wheezy
    command: echo hola debian
    parameters:
      - "-p=80"
      - "--net=host"

  - &cache
    name: cache
    image: centos:centos6
    command: echo hola centos
    parameters:
      - "-p=8080"
      - "--net=bridge"